eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/review_db
    username: root
    password: review123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
  application:
    name: reveiw-service
app:
  product:
    discount-rate: 30
